#!/usr/bin/env bash

. conf

buildDockerImg() {
    echo "Building Docker toolchain container"
    echo "In $PWD:"
    cat << EOF > Dockerfile
FROM dockcross/$dockxArch:$dockxTag

RUN \\
  dpkg --add-architecture $debArch && \\
  echo 'deb-src http://deb.debian.org/debian bullseye main' \\
    >> /etc/apt/sources.list && \\
  apt-get update && \\
  apt-get install --no-install-recommends --yes \\
    autopoint \\
    apt-utils \\
    apt-rdepends && \\
  apt-get clean autoclean --yes && \\
  apt-get autoremove --yes && \\
  rm -rf /var/lib/{apt,dpkg,cache,log}/

ENV DEFAULT_DOCKCROSS_IMAGE $dockerImg:latest
EOF

    docker build -t "$dockerImg" .
    docker run --rm "$dockerImg" > "./$dockxScript"
    chmod +x "./$dockxScript"
}

buildDockerImg
./$dockxScript bash ./script
